In [20]:
import numpy as np
rng = np.random.default_rng()

In [21]:
x = rng.integers(low = 3, high = 100, size = (5,4))
x

array([[12, 87, 84, 62],
       [45, 49,  5, 28],
       [19, 68, 95,  9],
       [21, 47,  9, 84],
       [48, 40, 48, 94]])

In [22]:
y = rng.integers(low = 3, high = 100, size = (2,4))
y

array([[39, 41, 93, 90],
       [59,  4, 74, 29]])

In [26]:
np.square(x - y[0])

array([[ 729, 2116,   81,  784],
       [  36,   64, 7744, 3844],
       [ 400,  729,    4, 6561],
       [ 324,   36, 7056,   36],
       [  81,    1, 2025,   16]])

In [30]:
np.sqrt(np.sum(np.square(x - y[0]), axis = 1))

array([ 60.90976933, 108.11105401,  87.71544904,  86.32496742,
        46.07602413])

In [31]:
dist = np.zeros((2,5))
dist

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [33]:
dist[0,:] = np.sqrt(np.sum(np.square(x - y[0]), axis = 1))

In [34]:
dist

array([[ 60.90976933, 108.11105401,  87.71544904,  86.32496742,
         46.07602413],
       [  0.        ,   0.        ,   0.        ,   0.        ,
          0.        ]])

In [38]:
for i in range(2):
            #######################################################################
            # TODO:                                                               #
            # Compute the l2 distance between the ith test point and all training #
            # points, and store the result in dists[i, :].                        #
            # Do not use np.linalg.norm().                                        #
            #######################################################################
        dist[i,:] = np.sqrt(np.sum(np.square(x - y[i])))
dist

array([[180.74014496, 180.74014496, 180.74014496, 180.74014496,
        180.74014496],
       [201.66308537, 201.66308537, 201.66308537, 201.66308537,
        201.66308537]])

In [39]:
x

array([[12, 87, 84, 62],
       [45, 49,  5, 28],
       [19, 68, 95,  9],
       [21, 47,  9, 84],
       [48, 40, 48, 94]])

In [56]:
xp = np.power(x,2).sum(axis=1, keepdims = 1).T
xp

array([[18613,  5235, 14091,  9787, 15044]])

In [57]:
yp = np.power(y,2).sum(axis=1, keepdims = 1)
yp

array([[19951],
       [ 9814]])

In [58]:
xp + yp

array([[38564, 25186, 34042, 29738, 34995],
       [28427, 15049, 23905, 19601, 24858]])

In [59]:
yx = -2*(y @ x.T)
yx

array([[-34854, -13498, -26348, -22286, -32872],
       [-18140,  -8066, -17368,  -9058, -18540]])

In [60]:
xp + yp + yx

array([[ 3710, 11688,  7694,  7452,  2123],
       [10287,  6983,  6537, 10543,  6318]])

In [62]:
a = rng.integers(low = 0, high = 80, size = (4,5))
b = rng.integers(low = 0, high = 80, size = (4,5))

In [63]:
b

array([[14, 60, 19, 18, 60],
       [32, 39, 37, 33, 38],
       [72,  8, 17, 37, 55],
       [50, 40, 48, 48, 39]])

In [67]:
np.array_split(b, 2)

[array([[14, 60, 19, 18, 60],
        [32, 39, 37, 33, 38]]),
 array([[72,  8, 17, 37, 55],
        [50, 40, 48, 48, 39]])]

In [70]:
np.concatenate([a,b], axis = 0)

array([[29, 76, 58, 53,  1],
       [16, 57, 18, 63, 72],
       [23, 54, 50, 41, 56],
       [35, 63, 54, 36, 75],
       [14, 60, 19, 18, 60],
       [32, 39, 37, 33, 38],
       [72,  8, 17, 37, 55],
       [50, 40, 48, 48, 39]])